/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  parenting_babies: () => import("@/views/parenting/babies/index.vue"),
  parenting_categories: () => import("@/views/parenting/categories/index.vue"),
  parenting_comments: () => import("@/views/parenting/comments/index.vue"),
  "parenting_growth-logs": () => import("@/views/parenting/growth-logs/index.vue"),
  "parenting_growth-metrics": () => import("@/views/parenting/growth-metrics/index.vue"),
  parenting_posts: () => import("@/views/parenting/posts/index.vue"),
  parenting_reports: () => import("@/views/parenting/reports/index.vue"),
  parenting_stats: () => import("@/views/parenting/stats/index.vue"),
  parenting_tags: () => import("@/views/parenting/tags/index.vue"),
  parenting_topics: () => import("@/views/parenting/topics/index.vue"),
  parenting_users: () => import("@/views/parenting/users/index.vue"),
};
