/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'parenting',
    path: '/parenting',
    component: 'layout.base',
    meta: {
      title: '育儿平台',
      icon: 'mdi:baby-face-outline',
      order: 2,
      roles: ['R_ADMIN'],
      i18nKey: 'route.parenting'
    },
    children: [
      {
        name: 'parenting_babies',
        path: '/parenting/babies',
        component: 'view.parenting_babies',
        meta: {
          title: '宝宝档案',
          icon: 'mdi:baby-face',
          roles: ['R_ADMIN'],
          i18nKey: 'route.parenting_babies'
        }
      },
      {
        name: 'parenting_categories',
        path: '/parenting/categories',
        component: 'view.parenting_categories',
        meta: {
          title: '分类管理',
          icon: 'mdi:shape-outline',
          roles: ['R_ADMIN'],
          i18nKey: 'route.parenting_categories'
        }
      },
      {
        name: 'parenting_comments',
        path: '/parenting/comments',
        component: 'view.parenting_comments',
        meta: {
          title: '评论审核',
          icon: 'mdi:comment-multiple-outline',
          roles: ['R_ADMIN'],
          i18nKey: 'route.parenting_comments'
        }
      },
      {
        name: 'parenting_growth-logs',
        path: '/parenting/growth-logs',
        component: 'view.parenting_growth-logs',
        meta: {
          title: '成长日志',
          icon: 'mdi:clipboard-text-outline',
          i18nKey: 'route.parenting_growth-logs'
        }
      },
      {
        name: 'parenting_growth-metrics',
        path: '/parenting/growth-metrics',
        component: 'view.parenting_growth-metrics',
        meta: {
          title: '成长指标',
          icon: 'mdi:chart-line',
          i18nKey: 'route.parenting_growth-metrics'
        }
      },
      {
        name: 'parenting_posts',
        path: '/parenting/posts',
        component: 'view.parenting_posts',
        meta: {
          title: '帖子审核',
          icon: 'mdi:post-outline',
          roles: ['R_ADMIN'],
          i18nKey: 'route.parenting_posts'
        }
      },
      {
        name: 'parenting_reports',
        path: '/parenting/reports',
        component: 'view.parenting_reports',
        meta: {
          title: '举报处理',
          icon: 'mdi:alert-octagon-outline',
          roles: ['R_ADMIN'],
          i18nKey: 'route.parenting_reports'
        }
      },
      {
        name: 'parenting_stats',
        path: '/parenting/stats',
        component: 'view.parenting_stats',
        meta: {
          title: '社区统计',
          icon: 'mdi:chart-bar',
          roles: ['R_ADMIN'],
          i18nKey: 'route.parenting_stats'
        }
      },
      {
        name: 'parenting_tags',
        path: '/parenting/tags',
        component: 'view.parenting_tags',
        meta: {
          title: '标签管理',
          icon: 'mdi:tag-outline',
          roles: ['R_ADMIN'],
          i18nKey: 'route.parenting_tags'
        }
      },
      {
        name: 'parenting_topics',
        path: '/parenting/topics',
        component: 'view.parenting_topics',
        meta: {
          title: '话题管理',
          icon: 'mdi:format-list-bulleted',
          roles: ['R_ADMIN'],
          i18nKey: 'route.parenting_topics'
        }
      },
      {
        name: 'parenting_users',
        path: '/parenting/users',
        component: 'view.parenting_users',
        meta: {
          title: '用户管理',
          icon: 'mdi:account-multiple',
          roles: ['R_ADMIN'],
          i18nKey: 'route.parenting_users'
        }
      }
    ]
  }
];
